name: Print Folder Sizes

on:
  workflow_dispatch:

jobs:
  print-sizes:
    runs-on: ubuntu-latest
    steps:
      - name: Print sizes
        run: |
          echo "Checking folder sizes..."
          df -H
          sudo rm -f -R /usr/local/lib/android || true
          df -H
